OPERATORS :
ARTHEMATIC OPERATORS (+,-,*,/,%)
RELATIONAL OPERATORS (>,<,>=,<=,=,!=)
LOGICAL OPERATORS (AND, OR)
SPECIAL OPERATORS (IN, NOT IN ,BETWEEN, NOT BETWEEN, IS LIKE, NOT LIKE)
SUBQUERY OPERATORS (ALL, ANY)

25) WQTD DEATLIS OF EMPS IF EMPS ARE WORKING AS WAITER OR CHEF ?
SELECT *
FROM EMPS
WHERE JOB = "WAITER" OR JOB = "CHEF";

WHERE JOB = "WAITER" OR "CHEF" --IT IS NOT WORKING BECAUSE IT IS NOT A VALID SYNTAX

26) WQTD FNAME,DOB AND DOJ IF EMPS BORN IN THE YEAR 1995 ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB>="1994-12-31" AND DOB<="1996-01-01";

27) WQTD DETAILS EMPS IF EMPS AS WORKING AS SECURITY AND SETTING SALARY LESS THAN 80000 ?
SELECT *
FROM EMPS
WHERE JOB="SECURITY" AND SAL<="80000";

28) WQTD DETAILS OF EMPS WHO BORN AFTER THE YEAR 1987 AND WORKING AS WAITER,CHEFE,CLEANER OR DELIVERY AN EMPLOYEE IS MALE ?
SELECT *
FROM EMPS
WHERE (DOB>"1987-12-31") AND (JOB="WAITER" OR JOB="CHEFE" OR JOB="CLEANER" OR JOB="DELIVERY") AND GENDER="M";

29) WQTD ITEM NAME AND PRICE FROM MENU_ITEMS TABLE IF ITEM PRICE IS EITHER 250,350, OR 300 ?
SELECT NAME,PRICE
FROM MENU_ITEMS
WHERE PRICE=250 OR PRICE=350 OR PRICE=300;
	OR
WHERE PRICE IN(250,350,300);
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IN :
-----
IT IS A MULTI-VALUE OPERATOR WHICH TAKES MULTIPLE VALUES AT THE RHS AND SINGLE VALUE AT THE LHS
IT WORKS ON "OR" CONDTIONS.
WHEN TO USE : WHENEVER WE NEED TO COMPAIR/INCLUUDE MULTIPLE VALUES AT A TIME BASED ON "OR" CONDITON THEN WE USE "IN" OPERATOR
SYNTAXX:
-------		   LHS            RHS
	COLUMN_NAME/EXPRESSION IN(V1,V2,.....,Vn);


30) WQTD DETAILS OF EMPS IF EMPS ARE WORKING AS SECURITY,CHEF OR DELIVERY AND HIRED IN THE YEAR 2018 ?
SELECT *
FROM EMPS
WHERE JOB IN("SECURITY","CHEF","DELIVERY") AND DOJ>="2018-01-01" AND DOJ<="2018-12-31";

31) WQTD ITEM NAME FROM MENU_ITEMS TABLE  IF ITEM NAME IS EITHER MASALA DOSA OR FISH CURRY ?
SELECT NAME
FROM MENU_ITEMS
WHERE NAME IN("MASALA DOSA","FISH CURRY");

32) WQTD DETAILS OF EMPS IF EMPS SATAUS IS NOT BUSY OR OFFLINE ? (WITHOUT USING SPECIAL OPERATOR)
SELECT *
FROM EMPS
WHERE STATUS!="BUSY" AND STATUS!=("OFFLINE");
		OR
WHERE STATUS NOT IN("BUSY","OFFLINE");
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

NOT IN :
--------
IT IS A MULTIPLE-VALUE OPRATOR WHICH TASKS MUTILPE VSLUES AT THE RHS AND SINGLE VALUE AT THE LHS.
IT WORKS ON "AND" CONDITIONS
WHEN TO USE : WHENEVER WE USED TO AVOID MULYIPLE-VALUE AT A TIME BASED ON "AND" CONDITION THEN USE "NOT IN" OPERATOR
SYNTAXX:
-------		   LHS            RHS
	COLUMN_NAME/EXPRESSION NOT IN(V1,V2,.....,Vn);



33) WQTD DETAILS OF EMPS WHO BORN IN THE YEAR 1992 AND NOT WORKING AS MANAGER AND CHEF AND HIRED IN THE YEAR 2018 BUT NOT A FEMALE ?
SELECT *
FROM EMPS
WHERE DOB>="1992-01-01" AND DOB<=("1992-12-31") AND JOB NOT IN("MANAGER","CHEF") AND DOJ>="2018-01-01" AND DOJ<="2018-12-31" AND GENDER NOT IN("F");

34) WQTD FNAME AND SALARY IF EMPS ARE GETTING SALARY MORE THAN OR EQUAL TO 24000 AND LESS THAN OR EQUAL TO 75000 ?
SELECT FNAME,SAL
FROM EMPS
WHERE SAL>=24000 AND SAL<=75000;
		OR
WHERE SAL BETWEEN 24000 AND 75000;

BETWEEN :
---------
IT IS USED TO INCLUDE SOME RANGE OF VALUES.
SYNTAX :
--------					>=		    <=
	COLUMN_NAME/EXPRESSION BETWEEN LOWER_RANGE_VALUE AND UPPER_RANGE_VALUE;

35) WQTD FNAME,DOB,DOJ IF EMPS BORN IN THE YEAR 1993 ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB BETWEEN "1993-01-01" AND "1993-12-31";
		OR
WHERE DOB>="1993-01-01" AND DOB<="1993-12-31";

36) WQTD FNAME,LNAME,JOB,SALARY IF EMPS GETTING SALARY MORE THAN 24000 AND LESS THAN 50000 AND WORKING AS WAITER,CLEANER OR DELIVERY ?
SELECT FNAME,LNAME,JOB,SAL
FROM EMPS
WHERE SAL BETWEEN 24000+0.01 AND 50000-0.01 AND JOB IN("WAITER","CLEANER","DELIVERY");

37) WQTD FNAME AND DOJ IF EMPS JOINED IN THE YEAR 2019,2020 ?
SELECT FNAME,DOJ
FROM EMPS
WHERE DOJ BETWEEN "2019-01-01" AND "2020-12-31";


NOT BETWEEN:
IT IS USED TO EXCLUDE SOME RANGE OF VALUES.
SYNTAX :
--------					>=		    <=
	COLUMN_NAME/EXPRESSION NOT BETWEEN LOWER_RANGE_VALUE AND UPPER_RANGE_VALUE;


38) WQTD DETAILS OF EMPS HOW ARE NOT GETTING SALARY IN THE RANGE 35000 TO 45000 ?
SELECT *
FROM EMPS
WHERE SAL NOT BETWEEN 35000 AND 45000;

39) WQTD FNAME AND DOB IF EMPS NOT BORN IN THE YEAR 1988 ?
SELECT FNAME,DOB
FROM EMPS
WHERE DOB NOT BETWEEN "1988-01-01" AND "1988-12-31";


IS :
----
IT IS USED TO CHECK WHETHER THE COLUMN IS NULL OR NULL NOT. AND IT IS ONLY WORKING WITH NULL/NOT NULL.
SYNTAX :
--------
	COLUMN_NAME/EXPRESSION IS NULL/NOT NULL;

40) WQTD DETAILS OF EMPS WHO ARE HAVING REPORTING MANAGER ?
SELECT *
FROM EMPS
WHERE MGR IS NOT NULL;

41) WQTD FNAME AND COMMISSION IF EMPS ARE NOT GETTING ANY COMMISSION ?
SELECT FNAME,COMM
FROM EMPS
WHERE COMM IS NULL;

42) WQTD DETAILS OF EMPS WHO ARE ACTING AS CUSTOMER FRO THEIR COMPARY ?
SELECT *
FROM EMPS
WHERE CID IS NOT NULL;

43) WQTD DETAILS OF EMPS WHO ARE WORKING AS WAITER OR DELIVERY AND GETTING  SALARY IN THE RANGE 35000 TO 100000 AND HIRED IN THE YEAR 2018 AND NOT BORN IN THE YEAR 1996 AND NOT WORKING AS CHEF AND SECURITY AND MUST HAVE A REPORTING MANAGER ?
SELECT *
FROM EMPS
WHERE JOB IN ("WAITER","DELIVERY") AND
      SAL BETWEEN 35000 AND 100000 AND
      DOJ BETWEEN "2018-01-01" AND "2018-12-31" AND
      DOB NOT BETWEEN "1996-01-01" AND "1996-12-31" AND
      JOB NOT IN ("CHEF","SECURITY") AND
      MGR IS NOT NULL;

44) WQTD DETAILS OF EMPS WHO JOINED IN THE YEAR 2016 AND IN THE DATE 10 ?
SELECT *
FROM EMPS
WHERE DOJ IN ("2016-01-10","2016-02-10","2016-03-10","2016-04-10","2016-05-10","2016-06-10","2016-07-10","2016-08-10","2016-09-10","2016-10-10","2016-11-10","2016-12-10");


LIKE :
------
IT IS USED FOR PATTERN MATCHING.IT WILL INCLUDE THE DATA BASED ON THE PATTERN.
SYNTAX:
-------
	COLUMN_NAME/EXPRESSION LIKE "PATTERN_MATCHS";
%(PERCENTAGE) -> IT IS HOLDES n NUMBER OF CHARACTERS AT A TIME.
_(UNDERSCORE)-> IT IS HOLDES SINGLE CHARACTER AT A TIME.

45) WQTD FNAME OF EMPS IS STARTING WITH K ?
SELECT FNAME
FROM EMPS
WHERE FNAME LIKE "K%";

46) WQTD FNAME AND LNAME IF LNAME IS ENDING WITH Y ?
SELECT FNAME,LNAME
FROM EMPS
WHERE LNAME LIKE "%Y";

47) WQTD DETAILS OF EMPS IF FNAME CONATINS ATLEAST 2 "A" AND GETTING SALARY IN THE RANGE 40000 TO 1 LAKH ?
SELECT *
FROM EMPS
WHERE FNAME LIKE "%A%A%" AND SAL BETWEEN 40000 AND 100000;

48) WQTD FNAME,LNAME,JOB IF JOB CONTAINS A STRING "ER" CONTINOUS IN IT ?
SELECT FNAME,LNAME,JOB
FROM EMPS
WHERE JOB LIKE "%ER%";

49) WQTD FNAME IF FNAME IS STARTING WITH "S" OR "A" ?
SELECT FNAME
FROM EMPS
WHERE FNAME LIKE "S%" OR FNAME LIKE "A%";

50) WQTD DETAILS OF EMPS IF EMPS HIRED IN THE YEAR 2019 ?
SELECT *
FROM EMPS
WHERE DOJ LIKE "2019%";
	OR
WHERE DOJ LIKE "2019-__-__";

51) WQTD DETAILS OF EMPS HOW JOINED IN THE DATE 12 OR 01 ?
SELECT *
FROM EMPS
WHERE DOJ LIKE "____-__-12" OR DOJ LIKE "____-__-01";
		OR
WHERE DOJ LIKE "%12" OR DOJ LIKE "%01";

52) WQTD FNAME,DOB AND DOJ IF EMPS BORN IN THE MONTH JAN,FEB OR MARCH ?
SELECT FNAME,DOB,DOJ
FROM EMPS
WHERE DOB LIKE "____-01-__" OR DOB LIKE "____-02-__" OR DOB LIKE "____-03-__";

53) WQTD CUSTOMER NAME,EMAIL WHERE EMAIL IS ENDING WITH .COM?
SELECT NAME,EMAI
FROM CUSTOMERS
WHERE EMAIL LIKE "%.COM";

NOT LIKE :
----------
•IT IS USED FOR PATTERN MATCHING.
•IT WILL EXCLUDE THE DATA BASED ON PATTERN.

SYNTAX :
--------
	COLUMN_NAME/EPRESSION NOT LIKE "PATTERN_TO_MATCH";

54) WQTD FNAME OF EMPS IF FNAME IS NOT STARTING WITH F?
SELECT FNAME
FROM EMPS
WHERE FNAME NOT LIKE "F%";

55) WQTD DETAILS OF EMPS WHO WHERE NOT JOINED IN THE YEAR 2020 ?
SELECT *
FROM EMPS
WHERE DOJ NOT LIKE "2020%";

56) WQTD FNAME,LNAME IF EMPS FNAME IS NOT STARTING WITH A AND D ?
SELECT FNAME,LNAME
FROM EMPS
WHERE FNAME NOT LIKE "A%" AND FNAME NOT LIKE "D%";

57) WQTD FNAME,LANEM,JOB IF LNAME CONTAINS EXACTLY 3 CHARACTORS ?
SELECT FNAME,LNAME,JOB
FROM EMPS
WHERE LNAME LIKE "___";

58) WQTD FNAME,ANNUAL SALARY IF ANNUAL SALARY 2ND DIGIT IS 2 ?
SELECT FNAME,SAL*12 AS "ANNUAL SALARY"
FROM EMPS
WHERE SAL*12 LIKE "_2%";

59) WQTD DETAILS OF EMPS IF EMPLOYEE FNAME LAST 3RD CHARACTOR IS "E" AND LNAME 4TH CHARATOR IS "R" AND WORKING AS WAITER OR MANAGER BUT NOT A FEMALE ?
SELECT *
FROM EMPS
WHERE FNAME LIKE "%E__" AND LNAME LIKE "___R%" AND JOB IN ("WAITER","MANAGER") AND GENDER NOT IN ("F");

60) WQTD DETAILS OF EMPS WHOSE FNAME STARTING WITH VOWELS ? (IMP)
SELECT *
FROM EMPS
WHERE FNAME LIKE "A%" OR
      FNAME LIKE "E%" OR
      FNAME LIKE "I%" OR
      FNAME LIKE "O%" OR
      FNAME LIKE "U%";

61) WQTD FNAME,LNAME OF EMPLOYEE IF FNAME IS STARTING WITH VOWELS BUT LNAME IS NOT ENDING WITH VOWELS ? (IMP)
SELECT FNAME,LNAME
FROM EMPS
WHERE (FNAME LIKE "A%" OR
       FNAME LIKE "E%" OR
       FNAME LIKE "I%" OR
       FNAME LIKE "O%" OR
       FNAME LIKE "U%") AND
      (LNAME NOT LIKE "%A" AND
      LNAME NOT LIKE "%E" AND
      LNAME NOT LIKE "%I" AND
      LNAME NOT LIKE "%O" AND
      LNAME NOT LIKE "%U");

62) WQTD FNAME OF EMPS IS STARTING AND ENDING WITH SAME CHARACTOR ?
SELECT FNAME
FROM EMPS
WHERE FNAME LIKE "A%A" OR
      FNAME LIKE "B%B" OR
      FNAME LIKE "C%C" OR
      FNAME LIKE "D%D" OR
      FNAME LIKE "E%E" OR
      FNAME LIKE "F%F" OR
      FNAME LIKE "G%G" OR
      FNAME LIKE "H%H" OR
      FNAME LIKE "I%I" OR
      FNAME LIKE "J%J" OR
      FNAME LIKE "K%K" OR
      FNAME LIKE "L%L" OR
      FNAME LIKE "M%M" OR
      FNAME LIKE "N%N" OR
      FNAME LIKE "O%O" OR
      FNAME LIKE "P%P" OR
      FNAME LIKE "R%R" OR
      FNAME LIKE "S%S" OR
      FNAME LIKE "T%T" OR
      FNAME LIKE "U%U" OR
      FNAME LIKE "V%V" OR
      FNAME LIKE "W%W" OR
      FNAME LIKE "X%X" OR
      FNAME LIKE "Y%Y" OR
      FNAME LIKE "Z%Z";

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE EMPLOYEE(
ID INT,
NAME VARCHAR(20)
);

INSERT INTO EMPLOYEE VALUES (1,"SHA%SHANK"),(2,"RA%HU%L"),(3,"RA_KSHITH");


ESCAPE CHARACTOR (\) :
--------------------
•IT IS USED TO REMOVE SPECIAL BEHAAVIOUR FROM SPECIAL CHARATER.
•WE SHOULD USE ESCAPE CHARACTER JUST BEFORE THE SPECIAL CHARACTER.

63) WQTD NAME FROM EMPLOYEE TABLE IF NAME CONTAINS ATLEAST 1 % IN IT ?
SELECT NAME
FROM EMPLOYEE
WHERE NAME LIKE "%\%%";

64) WQTD NAME FROM EMPLOYEE TABLE IF NAME 3RD CHARACTER IS UNDERSCORE(_) ?
SELECT NAME
FROM EMPLOYEE
WHERE NAME LIKE"__\_%";